apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-inventario-pvc
  namespace: agricultura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-inventario
  namespace: agricultura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-inventario
  template:
    metadata:
      labels:
        app: postgres-inventario
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "inventario_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              value: "posgresDB" # Según tu configuración
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-inventario-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventario-service
  namespace: agricultura
spec:
  selector:
    app: postgres-inventario
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
