apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: agricultura
type: Opaque
data:
  postgres-password: YWRtaW4= # admin en base64
  postgres-user: cG9zdGdyZXM= # postgres en base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-facturacion-pvc
  namespace: agricultura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-facturacion
  namespace: agricultura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-facturacion
  template:
    metadata:
      labels:
        app: postgres-facturacion
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "facturacion_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-facturacion-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-facturacion-service
  namespace: agricultura
spec:
  selector:
    app: postgres-facturacion
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
