server:
  port: 0
spring:
  application:
    name: SERVICIO-INVENTARIO
  datasource:
    url: jdbc:postgresql://localhost:5432/inventario_db
    username: postgres
    password: posgresDB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin