apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-facturacion-config
  namespace: agricultura
data:
  application.yml: |
    server:
      port: 8083

    spring:
      application:
        name: facturacion-service
      datasource:
        url: jdbc:postgresql://postgres-facturacion-service:5432/facturacion_db
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      rabbitmq:
        host: rabbitmq-service
        port: 5672
        username: admin
        password: admin

    cola:
      facturacion: cola_facturacion

    central:
      service:
        url: http://ms-central-service:8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-facturacion
  namespace: agricultura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-facturacion
  template:
    metadata:
      labels:
        app: ms-facturacion
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z postgres-facturacion-service 5432; do echo waiting for postgres; sleep 2; done;",
            ]
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done;",
            ]
      containers:
        - name: ms-facturacion
          image: ms-facturacion:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
      volumes:
        - name: config-volume
          configMap:
            name: ms-facturacion-config
---
apiVersion: v1
kind: Service
metadata:
  name: ms-facturacion-service
  namespace: agricultura
spec:
  selector:
    app: ms-facturacion
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
